// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHkGAXg-Le1Udwzk5rjmDvjiosqWh-hU',
    appId: '1:112004068815:web:82337fdc67320d375fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    authDomain: 'fir-auth-6789b.firebaseapp.com',
    databaseURL: 'https://fir-auth-6789b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-6789b.appspot.com',
    measurementId: 'G-XSV2B7W9QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbsOyU8boVrgzcDgZOTlqMd_EFsZXI_wg',
    appId: '1:112004068815:android:923c0fe7b736e9205fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    databaseURL: 'https://fir-auth-6789b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-6789b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7dqoStjtrB6l2xkQT61MRzHmk-tTrPRM',
    appId: '1:112004068815:ios:ff32dca7d7c913085fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    databaseURL: 'https://fir-auth-6789b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-6789b.appspot.com',
    iosBundleId: 'com.example.urbanAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7dqoStjtrB6l2xkQT61MRzHmk-tTrPRM',
    appId: '1:112004068815:ios:ff32dca7d7c913085fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    databaseURL: 'https://fir-auth-6789b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-6789b.appspot.com',
    iosBundleId: 'com.example.urbanAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeHkGAXg-Le1Udwzk5rjmDvjiosqWh-hU',
    appId: '1:112004068815:web:71c959ca6177ac1c5fceba',
    messagingSenderId: '112004068815',
    projectId: 'fir-auth-6789b',
    authDomain: 'fir-auth-6789b.firebaseapp.com',
    databaseURL: 'https://fir-auth-6789b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-auth-6789b.appspot.com',
    measurementId: 'G-FMGMQ3GSS6',
  );
}
